services:
  - type: web
    name: svg-template-generator
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/ms-playwright